### PR TITLE
chore(json): update various dependencies

### PR DESCRIPTION
**Pull request by janl**
we should test this thoroughly.

* * *

This commit was sponsored by The Hoodie Firm.
You can hire The Hoodie Firm:

http://go.hood.ie/thehoodiefirm

### CODE REVIEW

**Comment by boennemann** [comment]
Just for reference as the tests pass right away in this case, but for future operations like this we might want to use [next-update](https://github.com/bahmutov/next-update).

**Comment by janl** [comment]
@boennemann good call, only problem is, our test suite isn’t good enough to catch subtle issues like that. We need to do some manual testing here, I should have been more clear.

**Comment by boennemann** [comment]
@jan That's been clear. As I said, just for reference, so we're aware for future cases where test aren't running ;)

**Comment by janl** [comment]
@boennemann gotcha, thanks :)

**Comment by boennemann** [comment]
This has already been merged onto `next`. At the current speed of development we won't need to release any more releases on master/4.x, except for maybe security fixes.

**Pull request closed without merging**
