### PR TITLE
WIP: feat enable account

### PR DESCRIPTION
**Pull request by boennemann**

### CODE REVIEW

**Comment by boennemann** [comment]
@gr2m This is my WIP state. I think the dbs the users plugin creates conflicts now. Need to flush the memory between tests.

**Comment by gr2m** [comment]
@boennemann let’s merge https://github.com/hoodiehq/hoodie-server-account/pull/34, then we can remove `pouchdb-admins` from `hoodie-server`.

I need to catch up with mails etc and will look into the PR later

**Comment by gr2m** [comment]
do you know what the error in gzip is about?

**Comment by gr2m** [comment]
Can you ellaborate how to reproduce the conflict errors, and where you flush memory between tests?

**Comment by gr2m** [comment]
Okay see the conflict error now when running `node test/integration/force-gzip.js`. Can we isolate the conflict problem from the gzip tests?

**Comment by gr2m** [comment]
I got it, PR incoming

**Comment by gr2m** [comment]
Also fixed in https://github.com/hoodiehq/hoodie-server-account/pull/34, with this commit https://github.com/hoodiehq/hoodie-server-account/commit/d2a828836a1cd32a25029957efb4f57487289a2a

**Comment by gr2m** [comment]
w00p :green_heart: 

next steps as I see it

- [ ] merge https://github.com/hoodiehq/hoodie-server-account/pull/34
- [ ] fix package.json to install hoodie-server-account from npm again
- [ ] next PR: enable store
- [ ] create simple app with `npm install --save hoodie@next` to make sure it all works
- [ ] fix what’s left to fix
- [ ] https://www.youtube.com/watch?v=wyz_2DEah4o
- [ ] create a ton issue, starters where possible, add `ready` tag to show that community can pick them up

**Comment by gr2m** [comment]
current blockers:

Current implementation of `hoodie-server-store` needs a CouchDB URL:
https://github.com/hoodiehq/hoodie-server/blob/feat-enable-account/lib/hapi.js#L37

How do we create / destroy user databases and set `_security` when accounts get created / removed:
https://github.com/hoodiehq/hoodie-server/blob/feat-enable-account/lib/core-modules-glue-code/user-databases.js

@boennemann @christophwitzko how shall we implement these things? ^^

**Comment by janl** [comment]
CouchDB URL (bit of a hack): https://github.com/hoodiehq/hoodie-server-store/pull/3/files#diff-dd8e748922f3a4becde928fbe201ac13R5

Create/Delete DBs: create: `var db = new PouchDB(name)` delete: `db.destroy()` // e.g. we need access to raw PouchDB, but we could require that at this point.

_security I don’t know, but `db.add()` might just work

**Comment by janl** [comment]
> _security I don’t know, but db.put() might just work

ah nope, but we can use `db.request()`

**Comment by boennemann** [comment]
I really understand and appreciate all the excitement that's arising so close to the first working "next" release, but I don't think that we can move faster by pushing harder.
This PR now contains content for at least 5 different discussions and PRs and I don't agree with some things. Getting all of this sorted here blocks us forever.

Using one PR for one feature/fix served us well and so I reopened this as #437. It's only addressing the enabling of the account module, and leaves us with a discussion that we need to figure out, to unblock all following things anyway.

**Comment by gr2m** [comment]
this is never going to land, the approach in #437 looks good. I’ll continue the hacking in the `tent` branch to make things work together.

I’m sure we can have more productive discussions on how to do things proper once we see it working

**Comment by gr2m** [comment]
here is a first working version of new Hoodie:
https://github.com/hoodiehq/my-first-hoodie/tree/something-tracker#local-setup-to-test-new-hoodie

It uses `hoodie#tent` which uses `hoodie-server#tent`, the rest is from npm.

[The first commit](https://github.com/hoodiehq/pouchdb-hoodie-api/commit/20295e03d7cbf832ae02fe7c74a19e3e8f1ce1c4) to the Hoodie is over 10 months ago. Amazing to see the pieces finally working together. 

Looking forward to replace the tent ductape with quality code, just as we did it in all the other modules.

I’m super excited for next year. We did it :) ^5

**Pull request closed without merging**
