### PR TITLE
Use Store Server APIs for access and database creates/destroys

### PR DESCRIPTION
**Pull request by gr2m**
While the APIs do not change with this PR, existing data must be migrated.

The Hoodie Store Server API uses a database (`hoodie-store`) to keep track of databases and user access. A document for the database `user/lsdlo55` looks like this

```json
{
   "_id": "db_user/lsdlo55",
   "_rev": "1-a01e6998fb10543ca0402e648dd1d048",
   "access": {
       "read": {
           "role": [
               "id:lsdlo55"
           ]
       },
       "write": {
           "role": [
               "id:lsdlo55"
           ]
       }
   }
}
```

A migration script would need to

1. Load all databases and find the ones with `user/` prefix
2. Create the `hoodie-store` database and set its _security to read-only by admins
3. Create a doc for each `user/...` database with a `db_` prefix and set access accordingly as shown in the example above'

We could add a migration script to hoodie-server which would run itself on startup. In that case no breaking change would be necessary and we could make this a feature release

### CODE REVIEW

**Comment by gr2m** [comment]
ping @hoodiehq/maintainers

**Comment by courajs** [comment]
Looks good to me!
I agree a migration would be good. Is there some sort of 'hoodie database version' that makes it easy to detect whether we need to migrate?

**Comment by gr2m** [comment]
there is no such thing as a hoodie database version at this point. Migrations is something we have to think about in general in future, for both Hoodie core and apps. For this case though I’d create a little script that gets run when booting the app to avoid a breaking release, and it should be easy to remove it in future together with other breaking changes

> Looks good to me!

@courajs Just an fyi: we are integrating with https://lgtm.co/ and it’s currently expecting 2 members of the maintainers team to comment with `LGTM` to make the `approvals/lgtm` integration pass

**Comment by courajs** [comment]
Will you be adding the migration in this PR or another?

**Comment by gr2m** [comment]
@courajs I’ll add it here, I already have it ready, all that’s left is tests. But while working on it I found problems with pouchdb-adapter-leveldown and express-pouchdb and I’m far down the rabbit hole :( I hope to be able to update the PR today

**Comment by gr2m** [comment]
I pushed a WIP commit withe the migrations https://github.com/hoodiehq/hoodie-server/pull/507/commits/f5e4f6d9231de991041fd8710aca8edc7659fefb

**Comment by gr2m** [comment]
Turns out that there is a big in `express-pouchdb` since forever that will store a database with the name `user/abc4567` as `user%2Fabc4567`, which is different from PouchDB’s built-in behavior, see https://github.com/pouchdb/express-pouchdb/pull/377.

And because of that, this will be a breaking change for apps not using CouchDB anyway, and I don’t see a point in adding a migration for that as well. I’d suggest we release this as a breaking change, but add a migration for apps using CouchDB as the backend, which usually are the apps in production, while PouchDB is used for development. That means production apps can simply upgrade without any migration necessary, and for the rest I’ll add instructions for people who need to migrate

**Comment by gr2m** [comment]
if you could review https://github.com/hoodiehq/hoodie-store-server/pull/59 that’d be great, we need it for this PR to work properly

**Comment by gr2m** [comment]
I updated the PR, this is ready for review @hoodiehq/maintainers. I’d like to merge & release this PR first: hoodiehq/hoodie-store-server#59

**Comment by gr2m** [comment]
All right, all set, including migration for CouchDB, and now 100% test coverage 👌

**Pull request merged**
