### PR TITLE
propose to install `hoodie-start@next`

### PR DESCRIPTION
**Pull request by Guria**
recommend local install so globally installed current `hoodie-start` is not affected

### CODE REVIEW

**Comment by Charlotteis** [comment]
:wave: 

1) This needs to be rebased before merging
2) LGTM ?

**Comment by Guria** [comment]
rebased

**Comment by gr2m** [comment]
I’d like to discuss this with @boennemann first to hear what he has in mind. If we plan to keep a global CLI like hoodie as it today, we want to keep the global install

**Comment by Guria** [comment]
@gr2m We could change it back to global when `hoodie@next` will be ready. I've proposed switch to local not to mess existing dev setups.

**Comment by gr2m** [comment]
gotcha, makes sense :)

**Comment by janl** [comment]
LGTM

**Pull request merged**
