### PR TITLE
docs: format options as table

### PR DESCRIPTION
**Pull request by emig**
Clarify options by setting them in a table.

### CODE REVIEW

**Comment by emig** [comment]
which port is binding by default? Was not stated so I put a temporal '?' let me know and I'll update the docs.

**Comment by gr2m** [comment]
LGTM, thanks Ernesto :)

**Comment by emig** [comment]
@gr2m check the question, what is the default port :)?

**Comment by gr2m** [comment]
oops :) Default port is `8080`

**Comment by Charlotteis** [comment]
LGTM! Thanks Ernesto!

**Pull request merged**
