### PR TITLE
Migrate to new Architecture

### PR DESCRIPTION
**Pull request by finnp**
Migrate to new architecture as of https://github.com/hoodiehq/hoodie/issues/458

### CODE REVIEW

**Comment by finnp** [comment]
Here are the PRs for
- hoodie-client https://github.com/hoodiehq/hoodie-client/pull/65
- hoodie-server https://github.com/hoodiehq/hoodie/issues/458

**Comment by HipsterBrown** [comment]
LGTM. Well done @finnp! :clap:

**Comment by gr2m** [comment]
Can you or someone please make the PR to `tent` branch? This is the one we currently use

**Comment by finnp** [comment]
Apparantly you can't change target branches on PR, So here's the new PR: #485

**Pull request closed without merging**
