### PR TITLE
docs(LICENSE): unify license accross all active repositories

### PR DESCRIPTION
**Pull request by coderbyheart**
This PR aims to unify the licenses accross all active repositories

It

- adds a *License* section to the end of the `README.md`
- updates the `package.json` to include the correct `license` and `author` properties
- adds a small boilerplate `LICENSE` file

This PR is based on [hoodie-client-store#77](https://github.com/hoodiehq/hoodie-client-store/pull/77).

### CODE REVIEW

**Comment by janl** [comment]
LGTM

**Comment by janl** [comment]
@gr2m can you lgtm this?

**Comment by gr2m** [comment]
@janl as owners, we can merge it even without PR state being green. I think for cases like this that’s ok. But yeah, LGTM :)

**Comment by janl** [comment]
oops, thx!

**Pull request merged**
