### PR TITLE
docs(readme): grammar!

### PR DESCRIPTION
**Pull request by Charlotteis**
Trying to get back into the swing of things when it comes to contributing to Hoodie, so here are some grammar edits for the README.

Also, I think this is my 24th Pull Request for 24pullrequests.com! :sparkles:

### CODE REVIEW

**Comment by gr2m** [comment]
LGTM. I would like to put a "very" between the L & G but that’ll break lgtm.io ;)

**Comment by Charlotteis** [comment]
LGTM :see_no_evil:

**Comment by Charlotteis** [comment]
It worked! Haha.

**Comment by gr2m** [comment]
:tada:

**Pull request merged**
