### PR TITLE
Cleanup of internal Hapi plugin structure

### PR DESCRIPTION
**Pull request by boennemann**
With this PR I've cleaned up the (folder)-structure for our internal hapi-plugins, which was unnecessarily deep, didn't have clear names and contained a lot of duplicated code.

I tried to get rid of these things. I explained the details with inlined comments.

Ready for review :)

### CODE REVIEW

**Comment by janl** [comment]
Looks all good on the surface, but running this in an existing app with more plugins defined gives me this:

```
> hoodie start -n

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.6.3 (node v0.10.36, npm 2.1.10, platform: darwin)

Initializing...
CouchDB started: http://127.0.0.1:6045
Waiting for CouchDB [---*--] SUCCESS 
Error: Plugin not found: hoodie-plugin-appcache
    at Object.exports.resolvePluginPath (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:149:13)
    at /Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:175:20
    at Array.map (native)
    at Object.exports.getPluginPaths (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:174:29)
    at Object.exports.readPlugins (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:118:23)
    at exports.load (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:20:32)
    at /Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:1080:20
    at iterate (/Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:146:13)
    at /Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:157:25
    at Request._callback (/Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:154:25)

Stopping CouchDB...

```

`node_modules/hoodie-plugin-appcache` does exist.

**Comment by janl** [comment]
The offending function is this:

```javascript
exports.resolvePluginPath = function (env_config, p) {
  var errorMessage = 'Plugin not found: ' + p;

  // module lookup
  if (!(p[0] === '.' || p[0] === '/')) {
    try {
      console.log(p + '/package.json');
      return path.dirname(require.resolve(p + '/package.json'));
    } catch (e) {
      throw new Error(errorMessage);
    }
  }
```

I added the `console.log()` and it prints: `hoodie-plugin-appcache/package.json`

Looks like a `node_modules/` is missing.

**Comment by janl** [comment]
Moved this to https://github.com/hoodiehq/hoodie-server/pull/354 where it belongs.

Can we add a fix for this to master and then rebase this PR on master?

**Comment by boennemann** [comment]
@janl Addressed here: https://github.com/hoodiehq/hoodie-server/pull/357
No need to rebase, git merge should do the job for us, no?

**Comment by janl** [comment]
@boennemann down on master, yes, but I’d like to run this PR in isolation, too :)

**Comment by janl** [comment]
merged #357 into master and rebased this one on master locally, the issue persists. ^^

**Comment by boennemann** [comment]
@janl fixed and rebased, should (finally) be good now :)

**Comment by boennemann** [comment]
@janl ping :)

**Comment by janl** [comment]
👍

**Pull request merged**
