### PR TITLE
Find files of dependencies with `require.resolve` to be dedupe save

### PR DESCRIPTION
**Pull request by boennemann**
Ready for review now. Please not only look at the files, but test it locally installing this branch in a local hoodie-app, because it touches quite some stuff. Read my comments on specific lines and commit message (bodies) for further explanation.

```
hoodie new myapp
cd myapp
n i -S hoodiehq/hoodie-server#fix-require-resolve-usage
hoodie start
```

As the title suggests I've tried to replace all code that tries to predict the location of a dependency's file on the disk, by assuming it's in `node_modules`, with the "the proper way™": `require.resolve`.

As things often are when you do them "the proper way™" this removes a lot of complexity and code, which looks intriguing, but please make sure in your review that it still behaves the same.

### CODE REVIEW

**Comment by janl** [comment]
screen shot 2015-07-03 at 23 32 58 

<3

**Comment by janl** [comment]
Great stuff! — I’mma run this locally tomorrow before +1ing it. It’s too late now, but great work!

**Comment by boennemann** [comment]
@janl Added one more commit, updated the OP and also 
```diff
+58 
-92
```

**Comment by boennemann** [comment]
screen shot 2015-07-04 at 02 11 34
Manual testing revealed that uikit isn't loaded properly, investigating.

**Comment by janl** [comment]
@gr2m which commit message?

**Comment by gr2m** [comment]
@jan this one: https://github.com/hoodiehq/hoodie-server/commit/a205f8a9e289bbb4503497811bfebe989b208d3d

**Comment by janl** [comment]
@gr2m what about the commit message?

**Comment by gr2m** [comment]
never mind, I thought it'd be of interest for you, because you added the feature to server the static html file from hoodie-server, for the GZIP check, and Stephan showed that there is a much nicer way using require.resolve

**Comment by janl** [comment]
@gr2m gotcha, thanks :)

**Comment by boennemann** [comment]
Addressed all open issues and squashed things together. 

@gr2m @janl

**Comment by gr2m** [comment]
@boennemann awesome! Looks good to me :ship:

**Comment by christophwitzko** [comment]
@boennemann :shipit:

**Comment by christophwitzko** [comment]
With now two +1s and @janl’s only [issue](https://github.com/hoodiehq/hoodie-server/commit/5947b9d17a81f9983e5674f71fd616d95ce860bf#commitcomment-12006003) addressed I will go ahead and merge this.

**Comment by janl** [comment]
nice one!

**Comment by janl** [comment]
Looks all good on the surface, but running this in an existing app with more plugins defined gives me this:

```
> hoodie start -n

.d$b.  .d$b.  .d$$$$$$b.    .d$$$$$$b.  .d$$$$$$b.  .d$b..d$$$$$$$$b.
$$$$$..$$$$$.$$$$$$$$$$$b .$$$$$$$$$$$b $$$$$$$$$$b $$$$$$$$$$$$$$$P'
$$$$$$$$$$$$d$$$$$$$$$$$$bd$$$$$$$$$$$$b$$$$$$$$$$$b$$$$$$$$$$$$$$$b.
$$$$$$$$$$$$Q$$$$$$$$$$$$PQ$$$$$$$$$$$$P$$$$$$$$$$$P$$$$$$$$$$$$$$$P'
$$$$$´`$$$$$'$$$$$$$$$$$$''$$$$$$$$$$$$'$$$$$$$$$$P $$$$$$$$$$$$$$$b.
'Q$P'  'Q$P'  'Q$$$$$$P'    'Q$$$$$$P'  'Q$$$$$$$P  'Q$P''Q$$$$$$$$P'

Version: 0.6.3 (node v0.10.36, npm 2.1.10, platform: darwin)

Initializing...
CouchDB started: http://127.0.0.1:6045
Waiting for CouchDB [---*--] SUCCESS 
Error: Plugin not found: hoodie-plugin-appcache
    at Object.exports.resolvePluginPath (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:149:13)
    at /Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:175:20
    at Array.map (native)
    at Object.exports.getPluginPaths (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:174:29)
    at Object.exports.readPlugins (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:118:23)
    at exports.load (/Users/jan/Work/hoodie/hoodie-server/lib/core/plugins.js:20:32)
    at /Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:1080:20
    at iterate (/Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:146:13)
    at /Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:157:25
    at Request._callback (/Users/jan/Work/hoodie/hoodie-server/node_modules/async/lib/async.js:154:25)

Stopping CouchDB...

```

`node_modules/hoodie-plugin-appcache` does exist.

**Comment by janl** [comment]
The offending function is this:

```javascript
exports.resolvePluginPath = function (env_config, p) {
  var errorMessage = 'Plugin not found: ' + p;

  // module lookup
  if (!(p[0] === '.' || p[0] === '/')) {
    try {
      console.log(p + '/package.json');
      return path.dirname(require.resolve(p + '/package.json'));
    } catch (e) {
      throw new Error(errorMessage);
    }
  }
```

I added the `console.log()` and it prints: `hoodie-plugin-appcache/package.json`

Looks like a `node_modules/` is missing.

**Comment by janl** [comment]
Here’s a version that works:

```javascript
  if (!(p[0] === '.' || p[0] === '/')) {
    try {
      return path.dirname(require.resolve(p + '/package.json'));
    } catch (e) {
      if (e.code === 'MODULE_NOT_FOUND') {
        try {
          // try again, we might be loading an npm link’ed module
          var module_path = env_config.cwd + '/node_modules/' + p + '/package.json';
          return path.dirname(require.resolve(module_path));
        } catch(e2) {
          throw new Error(errorMessage);
        }
      }
      throw new Error(errorMessage);
    }
  }

```

**Comment by janl** [comment]
also, we should have an integration test that tests npm-linking a plugin.

Also also, we should switch all these manual path concatenations to `path.join` or `path.resolve` to make sure this works on Windows.

**Comment by boennemann** [comment]
All done here: https://github.com/hoodiehq/hoodie-server/pull/357

**Pull request merged**
